# -*- coding: utf-8 -*-
"""Dataton_Fase_5_base_completa_sst2_V9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Illy8WR94Wosi9wXUbKJ1FrofR2EYtiz

# Datathon Fase 5 — Base Completa com Rotulagem de Sentimento por DistilBERT

Este notebook processa a base completa de reclamações financeiras, cria a variável alvo de sentimento com um modelo pré-treinado de linguagem, compara abordagens de modelagem e analisa as principais dores dos clientes.

## Objetivos
- realizar o pré-processamento textual das reclamações;
- criar a variável alvo de sentimento em formato binário (`positivo` e `negativo`);
- treinar um **baseline** com TF-IDF + Regressão Logística;
- treinar um modelo de **Deep Learning** com LSTM;
- analisar os principais temas das reclamações negativas por categoria de produto.

## Escolha do modelo de sentimento
Nesta versão, a rotulagem automática de sentimento é feita com o modelo **`distilbert/distilbert-base-uncased-finetuned-sst-2-english`**, um modelo de classificação de sentimento em inglês ajustado no conjunto SST-2. Ele retorna diretamente as classes `POSITIVE` e `NEGATIVE`, o que deixa a variável alvo mais aderente ao desafio proposto.

## 1. Instalações
"""

#!pip install nltk
#!pip install scikit-learn
#!pip install kagglehub pandas
#!pip install transformers
#!pip install tensorflow

"""## 2. Importações"""

import os
import re
import string
import unicodedata
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import kagglehub
import torch
import time
import tensorflow as tf

from transformers import pipeline
from collections import Counter
from wordcloud import WordCloud

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.metrics import roc_curve, roc_auc_score, precision_recall_curve
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.utils.class_weight import compute_class_weight
from sklearn.feature_extraction.text import CountVectorizer

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import GRU

"""## 3. Verificação da GPU"""

print("CUDA disponível:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("GPU não disponível")

"""## 4. Recursos do NLTK"""

nltk.download("punkt_tab")
nltk.download("stopwords")

"""## 5. Montagem do Google Drive e criação da pasta do projeto"""

from google.colab import drive
drive.mount('/content/drive')

PASTA_PROJETO = "/content/drive/MyDrive/artefatos_fase5_full_sst2"
os.makedirs(PASTA_PROJETO, exist_ok=True)

print("Pasta do projeto:", PASTA_PROJETO)

"""## 6. Funções auxiliares"""

def salvar_csv(df, nome_arquivo, pasta=PASTA_PROJETO):
    caminho = os.path.join(pasta, nome_arquivo)
    df.to_csv(caminho, index=False)
    print(f"Salvo: {caminho}")

def carregar_csv(nome_arquivo, pasta=PASTA_PROJETO):
    caminho = os.path.join(pasta, nome_arquivo)
    df = pd.read_csv(caminho)
    print(f"Carregado: {caminho}")
    return df

def salvar_objeto(obj, nome_arquivo, pasta=PASTA_PROJETO):
    caminho = os.path.join(pasta, nome_arquivo)
    joblib.dump(obj, caminho)
    print(f"Salvo: {caminho}")

def carregar_objeto(nome_arquivo, pasta=PASTA_PROJETO):
    caminho = os.path.join(pasta, nome_arquivo)
    obj = joblib.load(caminho)
    print(f"Carregado: {caminho}")
    return obj

"""## 7. Download da base"""

path = kagglehub.dataset_download("shashwatwork/consume-complaints-dataset-fo-nlp")
print("Dataset salvo em:", path)
print("Arquivos encontrados:", os.listdir(path))

"""## 8. Leitura da base"""

df = pd.read_csv(os.path.join(path, "complaints_processed.csv"))
df.head()

"""## 9. Inspeção inicial"""

print("Dimensão:", df.shape)
print("Colunas:", df.columns.tolist())
print("\nInformações gerais:")
df.info()

print("\nValores nulos:")
print(df.isnull().sum())

"""## 10. Limpeza estrutural"""

df = df.drop(columns=["Unnamed: 0"], errors="ignore")
df = df.dropna(subset=["narrative"])
df = shuffle(df, random_state=42).reset_index(drop=True)

print("Nova dimensão:", df.shape)
df.head()

"""## 11. Base completa"""

df_full = df.copy()
print("Dimensão da base completa:", df_full.shape)

"""## 12. Salvamento da base bruta"""

salvar_csv(df_full, "01_full_bruta.csv")

"""## 13. Funções de limpeza

São criadas duas versões do texto:

- **`narrative_classic`**: limpeza mais forte para o baseline clássico;
- **`narrative_dl`**: limpeza mais leve para preservar contexto no modelo de Deep Learning.
"""

stop_words = set(stopwords.words("english"))

def clean_text_classic(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = unicodedata.normalize("NFKD", text).encode("ASCII", "ignore").decode("utf-8")
    text = re.sub(r"\d+", " ", text)
    text = text.translate(str.maketrans({p: " " for p in string.punctuation}))
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words]
    tokens = [t for t in tokens if len(t) > 2]
    return " ".join(tokens)

def clean_text_dl(text):
    if not isinstance(text, str):
        return ""

    text = text.lower().strip()
    text = re.sub(r"\s+", " ", text)
    return text

"""## 14. Aplicação da limpeza textual"""

df_full["narrative_classic"] = df_full["narrative"].apply(clean_text_classic)
df_full["narrative_dl"] = df_full["narrative"].apply(clean_text_dl)

df_full[["narrative", "narrative_classic", "narrative_dl"]].head()

"""## 15. Salvamento da base tratada"""

salvar_csv(df_full, "02_full_tratada.csv")

"""## 16. Criação do modelo de sentimento

Nesta etapa, a variável alvo será gerada com o modelo **DistilBERT SST-2**, que retorna diretamente as classes `POSITIVE` e `NEGATIVE`.
"""

device = 0 if torch.cuda.is_available() else -1

sentiment_model = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
    device=device
)

print("Device do modelo:", sentiment_model.model.device)

"""## 17. Teste rápido do pipeline de sentimento"""

amostra_teste = df_full["narrative_dl"].fillna("").astype(str).tolist()[:512]

ini = time.time()

_ = sentiment_model(
    amostra_teste,
    batch_size=32,
    truncation=True,
    max_length=128
)

fim = time.time()

print("Tempo para 512 textos:", fim - ini)
print("Device do modelo:", sentiment_model.model.device)

"""## 18. Inferência de sentimento na base completa

A base completa é processada em blocos para reduzir risco de erro de memória e manter o uso da GPU mais estável.
"""

textos = df_full["narrative_dl"].fillna("").astype(str).tolist()

resultados = []
batch_loop = 1000
batch_gpu = 32

for i in range(0, len(textos), batch_loop):
    lote = textos[i:i+batch_loop]

    saida = sentiment_model(
        lote,
        batch_size=batch_gpu,
        truncation=True,
        max_length=128
    )

    resultados.extend(saida)
    print(f"Lote processado: {i} até {i+len(lote)}")

"""## 19. Criação da variável alvo e salvamento da base rotulada

Como o modelo escolhido retorna somente `POSITIVE` e `NEGATIVE`, a variável `sentiment` é convertida diretamente para:

- `1` → positivo
- `-1` → negativo
"""

df_full["sentiment_raw"] = [r["label"] for r in resultados]
df_full["sentiment_score"] = [r["score"] for r in resultados]

df_full["sentiment_raw"] = df_full["sentiment_raw"].astype(str).str.upper().str.strip()

df_full["sentiment"] = df_full["sentiment_raw"].map({
    "POSITIVE": 1,
    "NEGATIVE": -1
})

print("Distribuição sentiment_raw:")
print(df_full["sentiment_raw"].value_counts(dropna=False))

print("\nDistribuição sentiment:")
print(df_full["sentiment"].value_counts(dropna=False))

salvar_csv(df_full, "03_full_com_sentimento_sst2.csv")

"""## 20. Distribuição dos sentimentos"""

contagem_sentimento = df_full["sentiment"].value_counts(dropna=False)
print(contagem_sentimento)

contagem_sentimento.plot(kind="bar")
plt.title("Distribuição dos sentimentos")
plt.ylabel("Quantidade")
plt.show()

"""## 21. Criação da base binária completa

Nesta versão, a base já é naturalmente binária. Ainda assim, mantemos a etapa de filtragem para garantir consistência metodológica.
"""

df_full_binario = df_full[df_full["sentiment"].isin([1, -1])].copy()
print(df_full_binario["sentiment"].value_counts())

"""## 22. Salvamento da base binária"""

salvar_csv(df_full_binario, "03a_full_binario_sst2.csv")

"""# =========================================
# DATA AUGMENTATION DA CLASSE POSITIVA
# =========================================
"""

# 1. Separar positivos e negativos
df_pos = df_full_binario[df_full_binario["sentiment"] == 1].copy()
df_neg = df_full_binario[df_full_binario["sentiment"] == -1].copy()

print("Positivos reais:", len(df_pos))
print("Negativos reais:", len(df_neg))

# 2. Oversampling dos positivos reais
# aqui vamos multiplicar a classe positiva por amostragem com reposição
n_oversample = 10000

df_pos_over = df_pos.sample(
    n=n_oversample,
    replace=True,
    random_state=42
).copy()

print("Positivos após oversampling:", len(df_pos_over))

# 3. Gerar positivos sintéticos com GPT-2
generator = pipeline(
    "text-generation",
    model="gpt2",
    device=0 if torch.cuda.is_available() else -1
)

prompts = [
    "The company resolved my issue and",
    "The bank service was excellent and",
    "I am satisfied with the support because",
    "The issue was fixed quickly and",
    "Customer service helped me and"
]

novas_frases = []
n_gpt = 3000  # quantidade de frases sintéticas

for i in range(n_gpt):
    prompt = prompts[i % len(prompts)]

    texto = generator(
        prompt,
        max_length=40,
        num_return_sequences=1,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95
    )[0]["generated_text"]

    novas_frases.append(texto)

df_gpt = pd.DataFrame({
    "narrative": novas_frases,
    "narrative_classic": novas_frases,
    "narrative_dl": novas_frases,
    "sentiment_raw": "POSITIVE",
    "sentiment_score": 1.0,
    "sentiment": 1
})

print("Positivos sintéticos GPT:", len(df_gpt))

# 4. Juntar positivos reais + oversampling + GPT
df_pos_aug = pd.concat([df_pos, df_pos_over, df_gpt], axis=0)
df_pos_aug = shuffle(df_pos_aug, random_state=42).reset_index(drop=True)

print("Total positivos aumentados:", len(df_pos_aug))

"""# 23. SEPARAÇÃO ENTRE TREINO REAL E TESTE REAL

A base balanceada será utilizada no modelo de Deep Learning e também em um experimento comparativo com o baseline.
"""

train_real, test_real = train_test_split(
    df_full_binario,
    test_size=0.2,
    stratify=df_full_binario["sentiment"],
    random_state=42
)

print("Treino real:")
print(train_real["sentiment"].value_counts())

print("\nTeste real:")
print(test_real["sentiment"].value_counts())

"""## 24. Data augmentation da classe positiva no treino"""

df_pos = train_real[train_real["sentiment"] == 1].copy()
df_neg = train_real[train_real["sentiment"] == -1].copy()

print("Positivos reais no treino:", len(df_pos))
print("Negativos reais no treino:", len(df_neg))

# oversampling simples da classe positiva
df_pos_over = df_pos.sample(
    n=len(df_neg),
    replace=True,
    random_state=42
).copy()

df_train_balanceado = pd.concat([df_neg, df_pos_over], axis=0)
df_train_balanceado = shuffle(df_train_balanceado, random_state=42).reset_index(drop=True)

print("\nBase de treino balanceada:")
print(df_train_balanceado["sentiment"].value_counts())

"""## 25. Salvar base de treino balanceada"""

salvar_csv(df_train_balanceado, "03c_train_balanceado.csv")
salvar_csv(test_real, "03d_test_real.csv")

"""## **RECOMECE AQUI**
Carregar base balanceada salva
comentar antes da entrega
"""

df_train_balanceado = pd.read_csv(f"{PASTA_PROJETO}/03c_train_balanceado.csv")
test_real = pd.read_csv(f"{PASTA_PROJETO}/03d_test_real.csv")

print("Treino balanceado:")
print(df_train_balanceado["sentiment"].value_counts())

print("\nTeste real:")
print(test_real["sentiment"].value_counts())

"""## 26. Modelo Baseline — Representação TF-IDF e Regressão Logística

Como ponto de partida, foi construído um modelo baseline utilizando TF-IDF para vetorização textual e Regressão Logística para classificação.  
O objetivo do baseline é estabelecer uma referência de desempenho para comparação com o modelo de Deep Learning.
"""

X_train_bal = df_train_balanceado["narrative_classic"]
y_train_bal = df_train_balanceado["sentiment"]

X_test_bal = test_real["narrative_classic"]
y_test_bal = test_real["sentiment"]

print("Treino baseline:", X_train_bal.shape, y_train_bal.shape)
print("Teste baseline:", X_test_bal.shape, y_test_bal.shape)

"""## 27. Baseline — TF-IDF"""

vectorizer_bal = TfidfVectorizer(max_features=5000)
X_train_bal_tfidf = vectorizer_bal.fit_transform(X_train_bal)
X_test_bal_tfidf = vectorizer_bal.transform(X_test_bal)

print("TF-IDF treino:", X_train_bal_tfidf.shape)
print("TF-IDF teste:", X_test_bal_tfidf.shape)

"""### 28. Baseline — treinamento"""

baseline_bal = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

baseline_bal.fit(X_train_bal_tfidf, y_train_bal)
y_pred_bal = baseline_bal.predict(X_test_bal_tfidf)
y_prob_bal = baseline_bal.predict_proba(X_test_bal_tfidf)

"""## 29. Baseline — avaliação"""

print("Accuracy:", accuracy_score(y_test_bal, y_pred_bal))
print("F1 (negative):", f1_score(y_test_bal, y_pred_bal, pos_label=-1))
print("F1 macro:", f1_score(y_test_bal, y_pred_bal, average="macro"))
print("\nRelatório de classificação:")
print(classification_report(y_test_bal, y_pred_bal))

"""## 30. Baseline — matriz de confusão"""

cm_bal = confusion_matrix(y_test_bal, y_pred_bal)
sns.heatmap(cm_bal, annot=True, fmt="d", cmap="Greens")
plt.title("Matriz de confusão - Baseline")
plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

"""## 31. Modelo Deep Learning — Tokenização e Sequências

Para capturar relações semânticas mais complexas no texto, foi utilizado um modelo de Deep Learning baseado em redes neurais recorrentes (GRU), que permite analisar a sequência das palavras e o contexto das frases.


"""

X_train_dl_text = df_train_balanceado["narrative_dl"].astype(str)
y_train_dl = df_train_balanceado["sentiment"].map({-1: 0, 1: 1})

X_test_dl_text = test_real["narrative_dl"].astype(str)
y_test_dl = test_real["sentiment"].map({-1: 0, 1: 1})

max_words = 15000
max_len = 100

tokenizer_dl = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer_dl.fit_on_texts(X_train_dl_text)

X_train_seq = tokenizer_dl.texts_to_sequences(X_train_dl_text)
X_test_seq = tokenizer_dl.texts_to_sequences(X_test_dl_text)

X_train_dl = pad_sequences(X_train_seq, maxlen=max_len, padding="post", truncating="post")
X_test_dl = pad_sequences(X_test_seq, maxlen=max_len, padding="post", truncating="post")

print("Treino DL:", X_train_dl.shape, y_train_dl.shape)
print("Teste DL:", X_test_dl.shape, y_test_dl.shape)

"""## 32. Deep Learning — pesos das classes"""

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train_dl)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train_dl
)

class_weights = dict(zip(classes, weights))
print("Pesos das classes:", class_weights)

"""## 33. Deep Learning — criação do modelo GRU"""

model_dl = Sequential([
    Embedding(input_dim=max_words, output_dim=128, input_length=max_len),
    GRU(64),
    Dense(32, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

model_dl.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

model_dl.summary()

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=2,
    restore_best_weights=True
)

"""## 34. Deep Learning — treinamento"""

history = model_dl.fit(
    X_train_dl,
    y_train_dl,
    validation_split=0.2,
    epochs=5,
    batch_size=64,
    callbacks=[early_stop],
    class_weight=class_weights,
    verbose=1
)

"""## 35. Deep Learning — avaliação"""

y_prob_dl = model_dl.predict(X_test_dl).ravel()
y_pred_dl = (y_prob_dl > 0.5).astype(int)

print("Accuracy DL:", accuracy_score(y_test_dl, y_pred_dl))
print("F1 macro DL:", f1_score(y_test_dl, y_pred_dl, average="macro"))
print("\nRelatório DL:")
print(classification_report(y_test_dl, y_pred_dl))

"""## 36. Deep Learning — matriz de confusão"""

cm_dl = confusion_matrix(y_test_dl, y_pred_dl)
sns.heatmap(cm_dl, annot=True, fmt="d", cmap="Blues")
plt.title("Matriz de confusão - Deep Learning (GRU)")
plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

"""## 37. Deep Learning — análise completa"""

# ROC Curve
fpr, tpr, _ = roc_curve(y_test_dl, y_prob_dl)
auc = roc_auc_score(y_test_dl, y_prob_dl)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc:.3f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.title("Curva ROC - Deep Learning")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.show()

# Precision-Recall Curve
precision, recall, _ = precision_recall_curve(y_test_dl, y_prob_dl)

plt.figure()
plt.plot(recall, precision)
plt.title("Curva Precision-Recall - Deep Learning")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

"""## 38. Deep Learning — ajuste de threshold"""

thresholds = np.arange(0.1, 0.9, 0.05)
f1_scores = []

for t in thresholds:
    y_pred_t = (y_prob_dl > t).astype(int)
    f1 = f1_score(y_test_dl, y_pred_t)
    f1_scores.append(f1)

plt.plot(thresholds, f1_scores)
plt.title("F1 Score vs Threshold")
plt.xlabel("Threshold")
plt.ylabel("F1 Score")
plt.show()

best_threshold = thresholds[np.argmax(f1_scores)]
print("Melhor threshold:", best_threshold)

y_pred_dl_best = (y_prob_dl > best_threshold).astype(int)

print("\nRelatório com melhor threshold:")
print(classification_report(y_test_dl, y_pred_dl_best))

"""## 39. Comparação entre os Modelos

Nesta etapa, comparamos o desempenho do modelo baseline e do modelo de Deep Learning utilizando métricas como:

- Acurácia
- Precision
- Recall
- F1-score
- ROC-AUC
- Precision-Recall

O objetivo é avaliar se o modelo de Deep Learning realmente apresenta ganho de desempenho em relação ao baseline.
"""

comparacao_modelos = pd.DataFrame({
    "Modelo": ["Baseline - Logistic Regression", "Deep Learning - GRU"],
    "Accuracy": [
        accuracy_score(y_test_bal, y_pred_bal),
        accuracy_score(y_test_dl, y_pred_dl)
    ],
    "F1_macro": [
        f1_score(y_test_bal, y_pred_bal, average="macro"),
        f1_score(y_test_dl, y_pred_dl, average="macro")
    ]
})

comparacao_modelos

"""## 40. Foco analítico nas reclamações negativas

Como o objetivo do projeto é entender as principais dores dos clientes, a análise foi concentrada nas reclamações com sentimento negativo.

A partir dessas reclamações, foram realizadas as seguintes análises:

- Produtos com maior volume de reclamações
- Palavras mais frequentes nas reclamações
- Bigramas (pares de palavras) mais frequentes
- Nuvem de palavras
- Frequência de reclamações por produto

Essa análise permite identificar padrões de problemas relatados pelos clientes e direcionar ações de melhoria.
"""

# carregar arquivo salvo
df_full = pd.read_csv(f"{PASTA_PROJETO}/03_full_com_sentimento_sst2.csv") # comentar antes da entrega

negative_df = df_full[df_full["sentiment"] == -1].copy()
print("Dimensão de negative_df:", negative_df.shape)
negative_df.head()

"""## 41. Salvar reclamações negativas"""

salvar_csv(negative_df, "10_negative_full.csv")

"""## 42. Produtos com mais reclamações negativas"""

negative_df["product"].value_counts().head(10).plot(kind="bar")
plt.title("Top categorias com reclamações negativas")
plt.ylabel("Quantidade")
plt.show()

"""## 43. Palavras mais frequentes"""

all_words = " ".join(negative_df["narrative_classic"])
word_freq = Counter(all_words.split())

top_words_df = pd.DataFrame(word_freq.most_common(20), columns=["word", "freq"])
top_words_df

"""## 44. Salvar palavras"""

salvar_csv(top_words_df, "11_top_words_negative_full.csv")

"""## 45. Nuvem de palavras e Bigramas das reclamações negativas

## 40. Foco analítico nas reclamações negativas

Como o objetivo do projeto é entender as principais dores dos clientes, a análise foi concentrada nas reclamações com sentimento negativo.

A partir dessas reclamações, foram realizadas as seguintes análises:

- Produtos com maior volume de reclamações
- Palavras mais frequentes nas reclamações
- Bigramas (pares de palavras) mais frequentes
- Nuvem de palavras
- Frequência de reclamações por produto

Essa análise permite identificar padrões de problemas relatados pelos clientes e direcionar ações de melhoria.
"""

wordcloud = WordCloud(width=1000, height=500, background_color="white").generate(all_words)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Nuvem de palavras - reclamações negativas")
plt.show()

vectorizer_bigram = CountVectorizer(
    stop_words="english",
    ngram_range=(2, 2),
    max_features=20
)

X_bigram = vectorizer_bigram.fit_transform(negative_df["narrative_classic"])

bigram_freq = pd.DataFrame({
    "Bigram": vectorizer_bigram.get_feature_names_out(),
    "Frequência": X_bigram.sum(axis=0).A1
}).sort_values(by="Frequência", ascending=False)

bigram_freq

plt.figure(figsize=(10,5))
plt.barh(bigram_freq["Bigram"], bigram_freq["Frequência"])
plt.gca().invert_yaxis()
plt.title("Principais dores dos clientes (Bigramas)")
plt.xlabel("Frequência")
plt.show()

salvar_csv(bigram_freq, "13_bigramas_reclamacoes.csv")

"""## 46. Frequência por produto"""

freq_por_produto = {}

for prod in negative_df["product"].value_counts().index:
    texto = " ".join(negative_df[negative_df["product"] == prod]["narrative_classic"])
    freq = Counter(texto.split()).most_common(10)
    freq_por_produto[prod] = freq

    print(f"\nProduto: {prod}")
    print(freq)

"""##47. Transformar frequências em tabela"""

linhas_freq_produto = []

for prod, lista_freq in freq_por_produto.items():
    for palavra, frequencia in lista_freq:
        linhas_freq_produto.append({
            "product": prod,
            "word": palavra,
            "freq": frequencia
        })

freq_produto_df = pd.DataFrame(linhas_freq_produto)
freq_produto_df

"""## 48. Salvar frequências por produto"""

salvar_csv(freq_produto_df, "12_freq_por_produto_full.csv")

"""## 49. Gráficos por produto"""

for prod in freq_produto_df["product"].unique():
    temp = freq_produto_df[freq_produto_df["product"] == prod]
    temp = temp.sort_values(by="freq", ascending=False).head(10)

    plt.figure(figsize=(10, 4))
    plt.bar(temp["word"], temp["freq"])
    plt.title(f"Top 10 palavras - {prod}")
    plt.xticks(rotation=45)
    plt.ylabel("Frequência")
    plt.xlabel("Palavras")
    plt.show()

"""## 50. Conclusão

A análise das reclamações permitiu identificar padrões importantes no comportamento e na insatisfação dos clientes em relação aos produtos e serviços financeiros.

A classificação de sentimento mostrou que a maior parte das reclamações possui sentimento negativo, indicando um alto nível de insatisfação dos clientes com os serviços analisados.

A análise textual das reclamações negativas permitiu identificar os principais temas de insatisfação, com destaque para problemas relacionados a:

- Cobranças indevidas
- Taxas e juros
- Problemas com cartão de crédito
- Atendimento ao cliente
- Empréstimos e financiamentos
- Demora na resolução de problemas

A análise por categoria de produto mostrou que alguns produtos concentram maior volume de reclamações, indicando áreas prioritárias para melhoria.

Do ponto de vista de negócio, os resultados indicam que a empresa deve priorizar melhorias nos processos relacionados a cobrança, atendimento ao cliente e gestão de crédito, pois esses temas concentram a maior parte das reclamações e impactam diretamente a satisfação dos clientes.

Além disso, o uso de modelos de Machine Learning e Deep Learning permite automatizar a classificação de sentimento em grandes volumes de reclamações, possibilitando que a empresa monitore a satisfação dos clientes em tempo real e identifique rapidamente novos problemas.
"""

print("Conclusão técnica:")
print("- A base completa foi rotulada com DistilBERT SST-2.")
print("- O treino foi balanceado por oversampling da classe positiva.")
print("- O teste foi realizado com base com distribuição real das classes.")
print("- Foram comparados um baseline com TF-IDF + Regressão Logística e um modelo de Deep Learning com GRU.")
print("- A análise de negócio foi focada nas reclamações negativas e nos produtos mais críticos.")